name: water_quality_probe
description: Mobile App for connecting and communicating with Bluetooth Low Energy devices, on Android, iOS, and MacOS.
#version: 1.34.5
#homepage: https://github.com/boskokg/flutter_blue_plus

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
#  flutter_map: ^7.0.2
#  latlong2: ^0.9.1  # Necesario para manejar coordenadas
  flutter_blue_plus: ^1.34.5
  get: ^4.6.6
  shared_preferences: ^2.0.0
  path_provider: ^2.0.15
  share_plus: ^10.1.3
  intl: ^0.17.0
#  share: ^2.0.4



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/